-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [spqr]: type definitions
import Aeneas
import Spqr.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace spqr

/-- Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 77:0-77:31
    Name pattern: [core::ops::arith::Add] -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 190:0-190:31
    Name pattern: [core::ops::arith::Sub] -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 324:0-324:31
    Name pattern: [core::ops::arith::Mul] -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::Div]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 462:0-462:31
    Name pattern: [core::ops::arith::Div] -/
@[rust_trait "core::ops::arith::Div"]
structure core.ops.arith.Div (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  div : Self → Rhs → Result Self_Output

/-- Trait declaration: [core::ops::arith::AddAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 769:0-769:37
    Name pattern: [core::ops::arith::AddAssign] -/
@[rust_trait "core::ops::arith::AddAssign"]
structure core.ops.arith.AddAssign (Self : Type) (Rhs : Type) where
  add_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::SubAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 840:0-840:37
    Name pattern: [core::ops::arith::SubAssign] -/
@[rust_trait "core::ops::arith::SubAssign"]
structure core.ops.arith.SubAssign (Self : Type) (Rhs : Type) where
  sub_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::MulAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 902:0-902:37
    Name pattern: [core::ops::arith::MulAssign] -/
@[rust_trait "core::ops::arith::MulAssign"]
structure core.ops.arith.MulAssign (Self : Type) (Rhs : Type) where
  mul_assign : Self → Rhs → Result Self

/-- Trait declaration: [core::ops::arith::DivAssign]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 964:0-964:37
    Name pattern: [core::ops::arith::DivAssign] -/
@[rust_trait "core::ops::arith::DivAssign"]
structure core.ops.arith.DivAssign (Self : Type) (Rhs : Type) where
  div_assign : Self → Rhs → Result Self

/-- [core::ops::range::RangeFull]
    Source: '/rustc/library/core/src/ops/range.rs', lines 44:0-44:20
    Name pattern: [core::ops::range::RangeFull] -/
@[reducible, rust_type "core::ops::range::RangeFull"]
def core.ops.range.RangeFull := Unit

/-- [libcrux_ml_kem::ind_cca::incremental::types::Error]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-ml-kem-0.0.7/src/ind_cca/incremental/types.rs', lines 14:0-14:14
    Name pattern: [libcrux_ml_kem::ind_cca::incremental::types::Error] -/
@[discriminant isize, rust_type
  "libcrux_ml_kem::ind_cca::incremental::types::Error"]
inductive libcrux_ml_kem.ind_cca.incremental.types.Error where
| InvalidInputLength : libcrux_ml_kem.ind_cca.incremental.types.Error
| InvalidOutputLength : libcrux_ml_kem.ind_cca.incremental.types.Error
| InvalidPublicKey : libcrux_ml_kem.ind_cca.incremental.types.Error
| InsufficientRandomness : libcrux_ml_kem.ind_cca.incremental.types.Error

/-- [libcrux_ml_kem::ind_cca::incremental::types::Ciphertext1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-ml-kem-0.0.7/src/ind_cca/incremental/types.rs', lines 155:0-155:40
    Name pattern: [libcrux_ml_kem::ind_cca::incremental::types::Ciphertext1] -/
@[rust_type "libcrux_ml_kem::ind_cca::incremental::types::Ciphertext1"]
structure libcrux_ml_kem.ind_cca.incremental.types.Ciphertext1 (LEN :
  Std.Usize) where
  value : Array Std.U8 LEN

/-- [libcrux_ml_kem::ind_cca::incremental::types::Ciphertext2]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-ml-kem-0.0.7/src/ind_cca/incremental/types.rs', lines 168:0-168:40
    Name pattern: [libcrux_ml_kem::ind_cca::incremental::types::Ciphertext2] -/
@[rust_type "libcrux_ml_kem::ind_cca::incremental::types::Ciphertext2"]
structure libcrux_ml_kem.ind_cca.incremental.types.Ciphertext2 (LEN :
  Std.Usize) where
  value : Array Std.U8 LEN

/-- Trait declaration: [rand_core::RngCore]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 130:0-130:17
    Name pattern: [rand_core::RngCore] -/
@[rust_trait "rand_core::RngCore"]
structure rand_core.RngCore (Self : Type) where
  next_u32 : Self → Result (Std.U32 × Self)
  next_u64 : Self → Result (Std.U64 × Self)
  fill_bytes : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

/-- Trait declaration: [rand::rng::Rng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand-0.9.1/src/rng.rs', lines 58:0-58:22
    Name pattern: [rand::rng::Rng] -/
@[rust_trait "rand::rng::Rng" (parentClauses := ["rand_coreRngCoreInst"])]
structure rand.rng.Rng (Self : Type) where
  rand_coreRngCoreInst : rand_core.RngCore Self

/-- Trait declaration: [rand_core::CryptoRng]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rand_core-0.9.3/src/lib.rs', lines 204:0-204:28
    Name pattern: [rand_core::CryptoRng] -/
@[rust_trait "rand_core::CryptoRng" (parentClauses := ["RngCoreInst"])]
structure rand_core.CryptoRng (Self : Type) where
  RngCoreInst : rand_core.RngCore Self

/-- [spqr::proto::pq_ratchet::PolynomialEncoder]
    Source: '/home/oliver/Projects/Verification/SparsePostQuantumRatchet/target/x86_64-unknown-linux-gnu/debug/build/spqr-026a0a30401f68eb/out/signal.proto.pq_ratchet.rs', lines 3:0-13:1 -/
structure proto.pq_ratchet.PolynomialEncoder where
  idx : Std.U32
  pts : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  polys : alloc.vec.Vec (alloc.vec.Vec Std.U8)

/-- [spqr::proto::pq_ratchet::PolynomialDecoder]
    Source: '/home/oliver/Projects/Verification/SparsePostQuantumRatchet/target/x86_64-unknown-linux-gnu/debug/build/spqr-026a0a30401f68eb/out/signal.proto.pq_ratchet.rs', lines 15:0-24:1 -/
structure proto.pq_ratchet.PolynomialDecoder where
  pts_needed : Std.U32
  polys : Std.U32
  pts : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  is_complete : Bool

/-- [spqr::encoding::gf::GF16]
    Source: 'src/encoding/gf.rs', lines 16:0-18:1 -/
structure encoding.gf.GF16 where
  value : Std.U16

/-- [spqr::encoding::polynomial::PolynomialError]
    Source: 'src/encoding/polynomial.rs', lines 13:0-20:1 -/
@[discriminant isize]
inductive encoding.polynomial.PolynomialError where
| MessageLengthEven : encoding.polynomial.PolynomialError
| MessageLengthTooLong : encoding.polynomial.PolynomialError
| SerializationInvalid : encoding.polynomial.PolynomialError

/-- [spqr::encoding::polynomial::Pt]
    Source: 'src/encoding/polynomial.rs', lines 26:0-29:1 -/
structure encoding.polynomial.Pt where
  x : encoding.gf.GF16
  y : encoding.gf.GF16

/-- [spqr::encoding::polynomial::Poly]
    Source: 'src/encoding/polynomial.rs', lines 79:0-88:1 -/
structure encoding.polynomial.Poly where
  coefficients : alloc.vec.Vec encoding.gf.GF16

/-- [spqr::encoding::polynomial::PolyConst]
    Source: 'src/encoding/polynomial.rs', lines 356:0-358:1 -/
structure encoding.polynomial.PolyConst (N : Std.Usize) where
  coefficients : Array encoding.gf.GF16 N

/-- [spqr::encoding::polynomial::const_polys_to_polys::closure]
    Source: 'src/encoding/polynomial.rs', lines 465:19-465:34 -/
@[reducible]
def encoding.polynomial.const_polys_to_polys.closure (N : Std.Usize) := Unit

/-- [spqr::encoding::polynomial::Point]
    Source: 'src/encoding/polynomial.rs', lines 513:0-516:1 -/
structure encoding.polynomial.Point where
  value : alloc.vec.Vec encoding.gf.GF16

/-- [spqr::encoding::polynomial::EncoderState]
    Source: 'src/encoding/polynomial.rs', lines 519:0-525:1 -/
@[discriminant isize]
inductive encoding.polynomial.EncoderState where
| Points :
  Array encoding.polynomial.Point 16#usize →
  encoding.polynomial.EncoderState
| Polys :
  Array encoding.polynomial.Poly 16#usize →
  encoding.polynomial.EncoderState

/-- [spqr::encoding::polynomial::PolyEncoder]
    Source: 'src/encoding/polynomial.rs', lines 528:0-531:1 -/
structure encoding.polynomial.PolyEncoder where
  idx : Std.U32
  s : encoding.polynomial.EncoderState

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::point_at::closure#1]
    Source: 'src/encoding/polynomial.rs', lines 640:25-643:21 -/
@[reducible]
def encoding.polynomial.PolyEncoder.point_at.closure_1 := Unit

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::point_at::closure]
    Source: 'src/encoding/polynomial.rs', lines 634:68-634:85 -/
@[reducible]
def encoding.polynomial.PolyEncoder.point_at.closure := Unit

/-- [spqr::encoding::EncodingError]
    Source: 'src/encoding.rs', lines 9:0-16:1 -/
@[discriminant isize]
inductive encoding.EncodingError where
| PolynomialError :
  encoding.polynomial.PolynomialError →
  encoding.EncodingError
| ChunkIndexDecodingError : encoding.EncodingError
| ChunkDataDecodingError : encoding.EncodingError

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyEncoder}::encode_bytes_base::closure]
    Source: 'src/encoding/polynomial.rs', lines 675:63-677:9 -/
@[reducible]
def encoding.polynomial.PolyEncoder.encode_bytes_base.closure := Slice Std.U8

/-- [spqr::encoding::Chunk]
    Source: 'src/encoding.rs', lines 25:0-28:1 -/
structure encoding.Chunk where
  index : Std.U16
  data : Array Std.U8 32#usize

/-- Trait declaration: [spqr::encoding::Encoder]
    Source: 'src/encoding.rs', lines 31:0-37:1 -/
structure encoding.Encoder (Self : Type) where
  encode_bytes : Slice Std.U8 → Result (core.result.Result Self
    encoding.EncodingError)
  next_chunk : Self → Result (encoding.Chunk × Self)

/-- [spqr::encoding::polynomial::PolyDecoder]
    Source: 'src/encoding/polynomial.rs', lines 741:0-760:1 -/
structure encoding.polynomial.PolyDecoder where
  pts_needed : Std.Usize
  pts : Array (sorted_vec.SortedSet encoding.polynomial.Pt.Insts.CoreCmpOrd)
    16#usize
  is_complete : Bool

/-- [spqr::encoding::polynomial::{spqr::encoding::polynomial::PolyDecoder}::new_with_poly_count::closure]
    Source: 'src/encoding/polynomial.rs', lines 787:38-787:58 -/
@[reducible]
def encoding.polynomial.PolyDecoder.new_with_poly_count.closure := Unit

/-- Trait declaration: [spqr::encoding::Decoder]
    Source: 'src/encoding.rs', lines 40:0-47:1 -/
structure encoding.Decoder (Self : Type) where
  new : Std.Usize → Result (core.result.Result Self encoding.EncodingError)
  add_chunk : Self → encoding.Chunk → Result Self
  decoded_message : Self → Result (Option (alloc.vec.Vec Std.U8))

/-- [spqr::incremental_mlkem768::Keys]
    Source: 'src/incremental_mlkem768.rs', lines 22:0-26:1 -/
structure incremental_mlkem768.Keys where
  ek : alloc.vec.Vec Std.U8
  dk : alloc.vec.Vec Std.U8
  hdr : alloc.vec.Vec Std.U8

/-- [spqr::serialize::Error]
    Source: 'src/serialize.rs', lines 7:0-12:1 -/
@[discriminant isize]
inductive serialize.Error where
| Deserialization : serialize.Error
| EncodingDecoding : serialize.Error

end spqr
